# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='ZUBIE')),
                ('f03', models.IntegerField(default=0, verbose_name='STATE')),
            ],
        ),
    ]
