# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='f02',
            field=models.CharField(default='.', max_length=99, verbose_name='ZUBIE'),
        ),
        migrations.AlterField(
            model_name='power',
            name='f01',
            field=models.IntegerField(default=0, verbose_name='ZUBIE ID'),
        ),
    ]
