# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20160929_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='TITLE')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='INFOTYPE')),
                ('f03', models.TextField(default='.', verbose_name='CONTENT')),
            ],
        ),
        migrations.CreateModel(
            name='Labstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='用户名')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='密码')),
                ('f03', models.CharField(default='.', max_length=99, verbose_name='姓名')),
                ('f04', models.CharField(default='.', max_length=99, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Labteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='用户名')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='密码')),
                ('f03', models.CharField(default='.', max_length=99, verbose_name='姓名')),
                ('f04', models.CharField(default='.', max_length=99, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Labtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='用户名')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='实验项目')),
                ('f03', models.CharField(default='.', max_length=99, verbose_name='申请状态')),
                ('f04', models.CharField(default='.', max_length=99, verbose_name='分数')),
                ('f05', models.CharField(default='.', max_length=99, verbose_name='申请时间')),
                ('f06', models.CharField(default='.', max_length=99, verbose_name='所属实验组')),
            ],
        ),
        migrations.RenameModel(
            old_name='Power',
            new_name='Labpower',
        ),
    ]
