# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20160929_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrjSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f00', models.CharField(default='.', max_length=99, verbose_name='編號')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='主題')),
                ('f02', models.CharField(default='.', max_length=99, verbose_name='說明')),
            ],
            options={
                'verbose_name': '項目需求說明',
                'verbose_name_plural': '項目需求說明',
            },
        ),
        migrations.AlterModelOptions(
            name='labinfo',
            options={'verbose_name': '信息', 'verbose_name_plural': '信息'},
        ),
        migrations.AlterModelOptions(
            name='labstudent',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelOptions(
            name='labteacher',
            options={'verbose_name': '老师', 'verbose_name_plural': '老师'},
        ),
    ]
