# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myidea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f00', models.CharField(default='.', max_length=99, verbose_name='編號')),
                ('f01', models.CharField(default='.', max_length=200, verbose_name='主題')),
                ('f02', models.CharField(default='.', max_length=2000, verbose_name='說明')),
            ],
        ),
    ]
